version: '3.8'

services:
  postgres:
    image: postgres:15
    container_name: postgres_sqlalchemy_playground
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: mypassword
      POSTGRES_DB: sqlalchemy1
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/my/path/to/customHTTPserver/postgresDB/data
volumes:
  postgres_data: