name: customHTTPserver
channels:
  - conda-forge
dependencies:
  - annotated-types=0.7.0
  - astroid=3.2.4
  - bzip2=1.0.8
  - ca-certificates=2024.8.30
  - colorama=0.4.6
  - dill=0.3.8
  - faker=28.4.1
  - isort=5.13.2
  - krb5=1.21.3
  - libcxx=18.1.8
  - libedit=3.1.20191231
  - libexpat=2.6.3
  - libffi=3.4.2
  - libpq=16.4
  - libsqlite=3.46.1
  - libzlib=1.3.1
  - mccabe=0.7.0
  - ncurses=6.5
  - openssl=3.3.2
  - pip=24.2
  - platformdirs=4.3.3
  - psycopg2=2.9.9
  - pydantic=2.9.1
  - pydantic-core=2.23.3
  - pylint=3.2.7
  - python=3.12.6
  - python-dateutil=2.9.0
  - python_abi=3.12
  - readline=8.2
  - setuptools=73.0.1
  - six=1.16.0
  - tk=8.6.13
  - tomli=2.0.1
  - tomlkit=0.13.2
  - typing-extensions=4.12.2
  - typing_extensions=4.12.2
  - tzdata=2024a
  - wheel=0.44.0
  - xz=5.2.6
