version: '3'
services: 
  mqtt-broker:
    image: eclipse-mosquitto:2.0.18
    container_name: mqtt-broker
    ports: 
      - "1883:1883"
    volumes:
      - ./mosquitto.conf:/mosquitto/config/mosquitto.conf
    networks:
      - host-network
    restart: unless-stopped
networks:
  host-network:
    driver: bridge